import "src/styles/globals.css";

import { Layout } from "src/components-server/Layout";
import { TrpcProvider } from "src/contexts/TrpcContext";
import { SessionProvider } from "src/contexts/SessionContext";
import { ThemeProvider } from "src/contexts/ThemeContext";

import { Montserrat } from "@next/font/google";

//const montserrat = Montserrat({ weight: "variable", subsets: ["latin"] });

//https://beta.nextjs.org/docs/optimizing/fonts#with-tailwind-css
//const oswald = Oswald({ weight: "variable", subsets: ["latin"], variable: "--font-paragraph" });
const fontparagraph = Montserrat({ weight: "variable", subsets: ["latin"], variable: "--font-paragraph" });

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={fontparagraph.variable}>
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <SessionProvider>
        <TrpcProvider>
          <ThemeProvider>
            <body>
              <Layout>{children}</Layout>
            </body>
          </ThemeProvider>
        </TrpcProvider>
      </SessionProvider>
    </html>
  );
}
