import "src/styles/globals.css";

import { Layout } from "src/components/Layout";
import { TrpcProvider } from "src/contexts/TrpcContext";
import { SessionProvider } from "src/contexts/SessionContext";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <SessionProvider>
        <TrpcProvider>
          <body>
            <Layout>{children}</Layout>
          </body>
        </TrpcProvider>
      </SessionProvider>
    </html>
  );
}
